# Generated by Django 4.2.23 on 2025-11-05 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plugins", "0013_alter_plugin_server"),
    ]

    operations = [
        migrations.AddField(
            model_name="pluginversion",
            name="supports_qt6",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Check this box if this version supports Qt6.",
                verbose_name="Supports Qt6",
            ),
        ),
    ]
