# Generated by Django 4.2.23 on 2025-09-25 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plugins", "0013_alter_plugin_server"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pluginversionfeedback",
            options={
                "verbose_name": "Plugin Version Feedback",
                "verbose_name_plural": "Plugin Version Feedbacks",
            },
        ),
        migrations.CreateModel(
            name="PluginVersionFeedbackAttachment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Upload screenshots or images to support your feedback",
                        upload_to="packages/%Y",
                        verbose_name="Image",
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True,
                        help_text="Optional caption for the image",
                        max_length=255,
                        null=True,
                        verbose_name="Caption",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created on"),
                ),
                (
                    "feedback",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="plugins.pluginversionfeedback",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feedback Attachment",
                "verbose_name_plural": "Feedback Attachments",
            },
        ),
    ]
