# Generated by Django 4.2.23 on 2026-01-08 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plugins", "0014_alter_pluginversionfeedback_options_and_more"),
        ("plugins", "0014_pluginversion_supports_qt6"),
    ]

    operations = []
