# Generated by Django 4.2.23 on 2025-12-08 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plugins", "0014_pluginversion_supports_qt6"),
    ]

    operations = [
        migrations.AddField(
            model_name="plugin",
            name="deleted_on",
            field=models.DateTimeField(
                blank=True,
                help_text="Date when the plugin was marked for deletion",
                null=True,
                verbose_name="Deleted on",
            ),
        ),
        migrations.AddField(
            model_name="plugin",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Plugin marked for deletion. Will be permanently deleted after one month.",
                verbose_name="Marked for deletion",
            ),
        ),
        migrations.AddField(
            model_name="pluginversion",
            name="deleted_on",
            field=models.DateTimeField(
                blank=True,
                help_text="Date when the version was marked for deletion",
                null=True,
                verbose_name="Deleted on",
            ),
        ),
        migrations.AddField(
            model_name="pluginversion",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Version marked for deletion. Will be permanently deleted after one month.",
                verbose_name="Marked for deletion",
            ),
        ),
    ]
