# Generated by Django 4.2.23 on 2025-12-10 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plugins", "0015_plugin_deleted_on_plugin_is_deleted_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pluginversion",
            name="deleted_on",
        ),
        migrations.RemoveField(
            model_name="pluginversion",
            name="is_deleted",
        ),
    ]
