# Generated by Django 4.2.23 on 2026-01-09 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plugins", "0015_merge_20260108_0425"),
        ("plugins", "0016_remove_version_soft_delete"),
    ]

    operations = []
