# Generated by Django 4.2.27 on 2026-01-13 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plugins", "0017_merge_20260109_0103"),
    ]

    operations = [
        migrations.CreateModel(
            name="PluginVersionSecurityScan",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scanned_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="Scanned on"),
                ),
                (
                    "total_checks",
                    models.IntegerField(default=0, verbose_name="Total checks"),
                ),
                (
                    "passed_checks",
                    models.IntegerField(default=0, verbose_name="Passed checks"),
                ),
                (
                    "warning_count",
                    models.IntegerField(default=0, verbose_name="Warnings"),
                ),
                (
                    "critical_count",
                    models.IntegerField(default=0, verbose_name="Critical issues"),
                ),
                (
                    "info_count",
                    models.IntegerField(default=0, verbose_name="Info items"),
                ),
                (
                    "files_scanned",
                    models.IntegerField(default=0, verbose_name="Files scanned"),
                ),
                (
                    "total_issues",
                    models.IntegerField(default=0, verbose_name="Total issues"),
                ),
                (
                    "scan_report",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Complete scan report with all check details",
                        verbose_name="Scan report",
                    ),
                ),
                (
                    "plugin_version",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="security_scan",
                        to="plugins.pluginversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plugin Version Security Scan",
                "verbose_name_plural": "Plugin Version Security Scans",
                "ordering": ["-scanned_on"],
            },
        ),
    ]
