# Generated by Django 4.2.27 on 2026-02-04 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plugins", "0018_pluginversionsecurityscan"),
    ]

    operations = [
        migrations.AddField(
            model_name="pluginversion",
            name="screenshot",
            field=models.ImageField(
                blank=True,
                help_text="Optional preview screenshot for the plugin. Maximum size: 2MB. Supported formats: PNG, JPG, JPEG, GIF.",
                null=True,
                upload_to="packages/%Y",
                verbose_name="Screenshot",
            ),
        ),
    ]
