# Generated by Django 4.2.29 on 2026-03-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plugins", "0019_remove_pluginversion_supports_qt6"),
    ]

    operations = [
        migrations.AddField(
            model_name="pluginversion",
            name="qt6_checked_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pluginversion",
            name="qt6_compatible",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pluginversion",
            name="qt6_logs",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="pluginversion",
            name="qt6_passed",
            field=models.BooleanField(null=True),
        ),
    ]
