# Generated by Django 4.2.28 on 2026-03-12 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0019_remove_pluginversion_supports_qt6'),
    ]

    operations = [
        migrations.AddField(
            model_name='pluginversion',
            name='validation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('validating', 'Validating'), ('validated', 'Validated'), ('blocked', 'Blocked')], db_index=True, default='pending', help_text="Validation status based on security and quality checks. New uploads start as 'validating' until checks complete. 'blocked' means critical issues were found and the version is not available for approval or download.", max_length=20, verbose_name='Validation status'),
        ),
    ]
