# Generated by Django 4.2.27 on 2026-02-04 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plugins", "0019_pluginversion_screenshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="plugin",
            name="screenshot",
            field=models.ImageField(
                blank=True,
                help_text="Default preview screenshot for the plugin. This will be used if no version-specific screenshot is available. Maximum size: 2MB. Supported formats: PNG, JPG, JPEG, GIF.",
                null=True,
                upload_to="packages/%Y",
                verbose_name="Screenshot",
            ),
        ),
    ]
