# Generated by Django 4.2.30 on 2026-05-19 10:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plugins", "0021_alter_pluginversionsecurityscan_scanned_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pluginversionsecurityscan",
            name="scanned_on",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="Scanned on",
            ),
        ),
        migrations.CreateModel(
            name="PluginEmailConfirmation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        help_text="The address being confirmed.",
                        max_length=254,
                        verbose_name="Email address",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        editable=False,
                        max_length=64,
                        unique=True,
                        verbose_name="Confirmation key",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Sent at"),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Confirmed at"
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Expires at")),
                (
                    "plugins",
                    models.ManyToManyField(
                        related_name="email_confirmations",
                        to="plugins.plugin",
                        verbose_name="Plugins",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plugin Email Confirmation",
                "verbose_name_plural": "Plugin Email Confirmations",
                "ordering": ["-sent_at"],
            },
        ),
    ]
