# Generated by Django 4.2.30 on 2026-04-30 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plugins', '0021_alter_pluginversionsecurityscan_scanned_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='pluginversionsecurityscan',
            name='enabled_rules_count',
            field=models.IntegerField(default=0, help_text='Number of rules that were enabled when this scan ran', verbose_name='Enabled rules count'),
        ),
        migrations.AddField(
            model_name='pluginversionsecurityscan',
            name='skipped_rules',
            field=models.JSONField(blank=True, default=list, help_text='List of rule codes that were skipped by the developer', verbose_name='Skipped rules'),
        ),
        migrations.AlterField(
            model_name='pluginversionsecurityscan',
            name='scanned_on',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Scanned on'),
        ),
        migrations.CreateModel(
            name='SecurityRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_category', models.CharField(choices=[('bandit', 'Bandit Security'), ('secrets', 'Detect Secrets'), ('flake8', 'Flake8 Quality'), ('file_analysis', 'File Analysis')], db_index=True, help_text='Security/quality tool category', max_length=50, verbose_name='Category')),
                ('check_code', models.CharField(db_index=True, help_text='Unique check identifier (e.g., B101, E501)', max_length=50, unique=True, verbose_name='Code')),
                ('check_name', models.CharField(help_text='Human-readable check name', max_length=200, verbose_name='Name')),
                ('check_description', models.TextField(help_text='Detailed description of what this check does', verbose_name='Description')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', help_text='Severity level of issues found by this check', max_length=20, verbose_name='Severity')),
                ('enabled', models.BooleanField(db_index=True, default=False, help_text='Whether this check is active (disabled by default)', verbose_name='Enabled')),
                ('can_be_skipped', models.BooleanField(default=True, help_text='Whether plugin developers can skip this check during upload', verbose_name='Can be skipped')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated on')),
            ],
            options={
                'verbose_name': 'Security Rule',
                'verbose_name_plural': 'Security Rules',
                'ordering': ['check_category', 'check_code'],
                'indexes': [models.Index(fields=['check_category', 'enabled'], name='plugins_sec_check_c_7b6a43_idx'), models.Index(fields=['enabled', 'can_be_skipped'], name='plugins_sec_enabled_530247_idx')],
            },
        ),
        migrations.CreateModel(
            name='PluginVersionSecurityRuleSkip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skipped_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Skipped on')),
                ('reason', models.TextField(blank=True, help_text='Optional reason for skipping this rule', verbose_name='Reason')),
                ('plugin_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skipped_security_rules', to='plugins.pluginversion')),
                ('security_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skipped_by_versions', to='plugins.securityrule')),
                ('skipped_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skipped_security_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plugin Version Security Rule Skip',
                'verbose_name_plural': 'Plugin Version Security Rule Skips',
                'ordering': ['-skipped_on'],
                'unique_together': {('plugin_version', 'security_rule')},
            },
        ),
    ]
