# Generated by Django 4.2.30 on 2026-05-06 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plugins", "0022_pluginversionsecurityscan_enabled_rules_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pluginversionsecurityscan",
            name="config_files_detected",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Config files found in the plugin ZIP that may have influenced scan results (e.g. .bandit, .secrets.baseline, .flake8)",
                verbose_name="Config files detected",
            ),
        ),
        migrations.AlterField(
            model_name="pluginversion",
            name="validation_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("validating", "Validating"),
                    ("validated", "Validated"),
                    ("validated_with_config", "Validated (configured)"),
                    ("blocked", "Blocked"),
                ],
                db_index=True,
                default="pending",
                help_text="Validation status based on security and quality checks. New uploads start as 'validating' until checks complete. 'blocked' means critical issues were found and the version is not available for approval or download.",
                max_length=25,
                verbose_name="Validation status",
            ),
        ),
    ]
