# Generated by Django 4.2.30 on 2026-06-11 02:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("plugins", "0023_pluginemailconfirmationerror"),
    ]

    operations = [
        migrations.CreateModel(
            name="PluginEmailCommunication",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=255, verbose_name="Subject")),
                ("body", models.TextField(verbose_name="Message")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "sent_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Sent at"),
                ),
                (
                    "recipient_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Recipient count"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=16,
                        verbose_name="Status",
                    ),
                ),
                (
                    "error",
                    models.TextField(
                        blank=True, default="", verbose_name="Error message"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_communications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plugin Email Communication",
                "verbose_name_plural": "Plugin Email Communications",
                "ordering": ["-created_at"],
            },
        ),
    ]
