# Generated by Django 4.2.30 on 2026-06-17 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plugins", "0024_pluginemailcommunication"),
    ]

    operations = [
        migrations.AddField(
            model_name="pluginemailconfirmation",
            name="superseded_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Superseded at"
            ),
        ),
    ]
