# Generated by Django 4.2.30 on 2026-06-24 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plugins", "0023_security_config_files"),
        ("plugins", "0024_pluginemailcommunication"),
    ]

    operations = []
