# Generated by Django 4.2.30 on 2026-06-25 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0025_merge_20260624_0308'),
        ('plugins', '0025_pluginversion_qt6_fields'),
    ]

    operations = [
    ]
