# Generated by Django 4.2.30 on 2026-07-12 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0025_pluginemailconfirmation_superseded_at'),
        ('plugins', '0026_merge_20260625_0147'),
    ]

    operations = [
    ]
