# Generated by Django 5.2.17 on 2026-09-14 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plugins", "0027_merge_20260712_2333"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plugin",
            name="rating_score",
        ),
        migrations.RemoveField(
            model_name="plugin",
            name="rating_votes",
        ),
    ]
