"""Drop the djangoratings tables.

The rating feature was removed from plugins.qgis.org (QGIS PSC, September 2026)
after sustained vote manipulation, and ``djangoratings`` leaves INSTALLED_APPS in
the same commit. Its four tables must go with it rather than being left in place:
``djangoratings_vote`` and ``djangoratings_ignoredobject`` hold real foreign keys
into ``auth_user`` and ``django_content_type``, so an orphaned table would make a
later ``User.delete()`` fail with an IntegrityError that Django can no longer
explain, because the model is gone from the app registry.

``IF EXISTS`` is required: on a fresh database (every test run) the app is not
installed, so these tables were never created and a bare DROP would abort the
whole migration.

There is deliberately no dependency on ``('djangoratings', ...)`` -- the app is
uninstalled in this same commit, so that node is not in the migration graph.

The reverse is the DDL emitted by ``manage.py sqlmigrate djangoratings
0001_initial`` on the last commit before removal, so constraint and index names
round-trip exactly. ``0002_ipaddr_field`` was already a no-op (the column is
created as ``inet``), so only its ``django_migrations`` row is restored.

Reversing restores the schema, not the data: the vote history is dropped without
being archived, by decision on issue #439.
"""

from django.db import migrations

FORWARD = """
DROP TABLE IF EXISTS djangoratings_vote CASCADE;
DROP TABLE IF EXISTS djangoratings_score CASCADE;
DROP TABLE IF EXISTS djangoratings_similaruser CASCADE;
DROP TABLE IF EXISTS djangoratings_ignoredobject CASCADE;
DELETE FROM django_migrations WHERE app = 'djangoratings';
"""

REVERSE = """
CREATE TABLE IF NOT EXISTS "djangoratings_ignoredobject" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "object_id" integer NOT NULL CHECK ("object_id" >= 0), "content_type_id" integer NOT NULL, "user_id" integer NOT NULL);
CREATE TABLE IF NOT EXISTS "djangoratings_score" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "object_id" integer NOT NULL CHECK ("object_id" >= 0), "key" varchar(32) NOT NULL, "score" integer NOT NULL, "votes" integer NOT NULL CHECK ("votes" >= 0), "content_type_id" integer NOT NULL);
CREATE TABLE IF NOT EXISTS "djangoratings_similaruser" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "agrees" integer NOT NULL CHECK ("agrees" >= 0), "disagrees" integer NOT NULL CHECK ("disagrees" >= 0), "exclude" boolean NOT NULL, "from_user_id" integer NOT NULL, "to_user_id" integer NOT NULL);
CREATE TABLE IF NOT EXISTS "djangoratings_vote" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "object_id" integer NOT NULL CHECK ("object_id" >= 0), "key" varchar(32) NOT NULL, "score" integer NOT NULL, "ip_address" inet NOT NULL, "cookie" varchar(32) NULL, "date_added" timestamp with time zone NOT NULL, "date_changed" timestamp with time zone NOT NULL, "content_type_id" integer NOT NULL, "user_id" integer NULL);

ALTER TABLE "djangoratings_vote" ADD CONSTRAINT "djangoratings_vote_content_type_id_object_i_49a66d8f_uniq" UNIQUE ("content_type_id", "object_id", "key", "user_id", "ip_address", "cookie");
ALTER TABLE "djangoratings_similaruser" ADD CONSTRAINT "djangoratings_similaruser_from_user_id_to_user_id_f7179a74_uniq" UNIQUE ("from_user_id", "to_user_id");
ALTER TABLE "djangoratings_score" ADD CONSTRAINT "djangoratings_score_content_type_id_object_id_key_aeb9c5b6_uniq" UNIQUE ("content_type_id", "object_id", "key");
ALTER TABLE "djangoratings_ignoredobject" ADD CONSTRAINT "djangoratings_ignoredobj_content_type_id_object_i_42171914_uniq" UNIQUE ("content_type_id", "object_id");

ALTER TABLE "djangoratings_ignoredobject" ADD CONSTRAINT "djangoratings_ignore_content_type_id_010c01fe_fk_django_co" FOREIGN KEY ("content_type_id") REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "djangoratings_ignoredobject" ADD CONSTRAINT "djangoratings_ignoredobject_user_id_ecbd28f9_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "djangoratings_ignoredobject_content_type_id_010c01fe" ON "djangoratings_ignoredobject" ("content_type_id");
CREATE INDEX "djangoratings_ignoredobject_user_id_ecbd28f9" ON "djangoratings_ignoredobject" ("user_id");
ALTER TABLE "djangoratings_score" ADD CONSTRAINT "djangoratings_score_content_type_id_adec7165_fk_django_co" FOREIGN KEY ("content_type_id") REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "djangoratings_score_content_type_id_adec7165" ON "djangoratings_score" ("content_type_id");
ALTER TABLE "djangoratings_similaruser" ADD CONSTRAINT "djangoratings_similaruser_from_user_id_0f3ced0a_fk_auth_user_id" FOREIGN KEY ("from_user_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "djangoratings_similaruser" ADD CONSTRAINT "djangoratings_similaruser_to_user_id_7ab88932_fk_auth_user_id" FOREIGN KEY ("to_user_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "djangoratings_similaruser_from_user_id_0f3ced0a" ON "djangoratings_similaruser" ("from_user_id");
CREATE INDEX "djangoratings_similaruser_to_user_id_7ab88932" ON "djangoratings_similaruser" ("to_user_id");
ALTER TABLE "djangoratings_vote" ADD CONSTRAINT "djangoratings_vote_content_type_id_57093104_fk_django_co" FOREIGN KEY ("content_type_id") REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "djangoratings_vote" ADD CONSTRAINT "djangoratings_vote_user_id_edecfa87_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "djangoratings_vote_content_type_id_57093104" ON "djangoratings_vote" ("content_type_id");
CREATE INDEX "djangoratings_vote_user_id_edecfa87" ON "djangoratings_vote" ("user_id");

INSERT INTO django_migrations (app, name, applied)
VALUES ('djangoratings', '0001_initial', NOW()),
       ('djangoratings', '0002_ipaddr_field', NOW())
ON CONFLICT DO NOTHING;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("plugins", "0028_remove_plugin_rating_fields"),
    ]

    operations = [
        migrations.RunSQL(FORWARD, reverse_sql=REVERSE),
    ]
